[project]
name = "infnum"
version = "0.1.0"
description = "Infinite and infinitesimal numbers for JAX"
authors = [
    { name = "Alok Singh", email = "alokbeniwal@gmail.com" }
]
dependencies = [
    "jax>=0.4.35",
    "jaxtyping>=0.2.34",
    "beartype>=0.19.0",
    "einops>=0.8.0",
    "hypothesis>=6.118.7",
    "jaxlib>=0.4.35",
    "numpy>=2.1.3",
    "scipy>=1.14.1",
    "fancy-einsum>=0.0.3",
]
readme = "README.md"
requires-python = ">= 3.12"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = [
    "hypothesis>=6.118.7",
    "pytest>=8.3.3",
]

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/infnum"]
